name: vscode-stable-release

on:
  push:
    tags:
      - vscode-v*

jobs:
  release:
    if: github.repository == 'sourcegraph/cody'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write # for publishing the release
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: .tool-versions
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # SECURITY: pin third-party action hashes
        with:
          run_install: true
      - name: get release version
        id: release_version
        run: |
          TAGGED_VERSION="${GITHUB_REF/refs\/tags\/vscode-v/}"

          if [[ ! "${TAGGED_VERSION}" =~ ^[0-9]+\.[0-9]+\.[0-9]+.*$ ]]; then
            echo "Invalid version tag '${TAGGED_VERSION}'"
            exit 1
          fi

          echo "EXT_VERSION=${TAGGED_VERSION}" >> $GITHUB_ENV
          WRITTEN_VERSION="$(cat vscode/package.json | jq '.version' -r)"

          if [[ "${TAGGED_VERSION}" != "${WRITTEN_VERSION}" ]]; then
            echo "Release tag and version in vscode/package.json do not match: '${TAGGED_VERSION}' vs. '${WRITTEN_VERSION}'"
            exit 1
          fi
      - run: pnpm build
      - run: pnpm run test
      - run: xvfb-run -a pnpm -C vscode run test:integration
      - run: xvfb-run -a pnpm -C vscode run test:e2e
        env:
          NO_LOG_TESTING_TELEMETRY_CALLS: true
      - run: CODY_RELEASE_TYPE=stable pnpm -C vscode run release
        if: github.repository == 'sourcegraph/cody'
        env:
          VSCODE_MARKETPLACE_TOKEN: ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}
          VSCODE_OPENVSX_TOKEN: ${{ secrets.VSCODE_OPENVSX_TOKEN }}
      - run: pnpm -C vscode run github-changelog
      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Cody for VS Code ${{ env.EXT_VERSION }}
          draft: false
          body_path: vscode/GITHUB_CHANGELOG.md
      - name: upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./vscode/dist/cody.vsix
          asset_name: cody-vscode-${{ env.EXT_VERSION }}.vsix
          asset_content_type: application/zip
      - name: Generate changelog
        env:
          DEVX_SERVICE_GH_TOKEN: ${{ secrets.DEVX_SERVICE_GH_TOKEN }}
          GH_REPO: "sourcegraph/cody"
          CHANGELOG_CATEGORY_ACCEPTLIST: "added,changed,fixed"
          CHANGELOG_SKIP_NO_CHANGELOG: "true"
          CHANGELOG_COMPACT: "true"
          EXT_VERSION: ${{ env.EXT_VERSION }}
        run: |
          # Get previous tag's commit
          PREV_TAG=$( git tag --sort=-v:refname | grep '^vscode-v' |  head -n 2 | tail -n 1)
          export RELEASE_LATEST_RELEASE=$(git rev-parse $PREV_TAG)

          # Get current release commit
          export RELEASE_LATEST_COMMIT=$GITHUB_SHA

          # Download and run changelog generator
          tagName=$(gh release -R sourcegraph/devx-service list --exclude-drafts --exclude-pre-releases -L 1 --json tagName -q '.[] | .tagName')
          gh release -R sourcegraph/devx-service download ${tagName} --pattern changelog
          chmod +x changelog

          ./changelog write \
          --output-file="raw-changelog.md" \
          --releaseregistry.version=$EXT_VERSION

          cat vscode/CHANGELOG.md >> raw-changelog.md
          mv raw-changelog.md vscode/CHANGELOG.md
          git checkout -b release/vscode-v$EXT_VERSION
          git add vscode/CHANGELOG.md
          git commit -m "Automated release and changelog for VS code Cody"
          git push -u origin release/vscode-v$EXT_VERSION
          gh pr create \
            --title "VS Code: Release v$EXT_VERSION" \
            --body "Automated release and changelog for VS code Cody" \
            --base main --head release/vscode-v$EXT_VERSION
      - name: Register on Releaseregistry
        env:
          EXT_VERSION: ${{ env.EXT_VERSION }}
          RELEASE_REGISTRY_TOKEN: ${{ secrets.RELEASE_REGISTRY_TOKEN }}
        run: |
          echo "Registering internal cody-vscode $EXT_VERSION release on release registry"
          body=$(wget --content-on-error -O- --header="Content-Type: application/json" --header="Authorization: ${RELEASE_REGISTRY_TOKEN}" --post-data '{
              "name": "cody-vscode",
              "version": "'${EXT_VERSION}'",
              "git_sha": "'${GITHUB_SHA}'"
            }' "https://releaseregistry.sourcegraph.com/v1/releases")
          exit_code=$?

          if [ $exit_code != 0 ]; then
            echo "❌ Failed to create release in release registry, got:"
            echo "--- raw body ---"
            echo $body
            echo "--- raw body ---"
            exit $exit_code
          else
            echo "Release created, see:"
            echo $body
          fi
      - name: Determine version numbers
        run: |
          tag="${{ env.EXT_VERSION }}"
          version_anchor=$(echo $tag | sed 's/[^0-9]//g')
          major=$(echo $tag | sed 's/\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\)/\1/')
          minor=$(echo $tag | sed 's/\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\)/\2/')
          next_minor=$(($minor + 2))
          echo "VERSION_ANCHOR=$version_anchor" >> $GITHUB_ENV
          echo "CURRENT_RELEASE_BRANCH=vscode-v$major.$minor.x" >> $GITHUB_ENV
          echo "NEXT_RELEASE_BRANCH=vscode-v$major.$next_minor.x" >> $GITHUB_ENV
      - name: 'Slack notification'
        run: |
          echo "Posting release announcement to Slack"
          ANNOUNCE_EDITORS_SLACK_WEBHOOK_URL=${{ secrets.ANNOUNCE_EDITORS_SLACK_WEBHOOK_URL }}

          # treat this like an array, add a space for the next webhook secret
          webhooks=("$ANNOUNCE_EDITORS_SLACK_WEBHOOK_URL")
          for webhook in "${webhooks[@]}"; do
            response=$(curl -s -w "%{http_code}" -X POST -H "Content-Type: application/json" -d '{
              "type": "mrkdwn",
              "text": ":cody: :vscode: Cody for VS Code `v${{ env.EXT_VERSION }}` has been published, see the <https://github.com/sourcegraph/cody/blob/main/vscode/CHANGELOG.md#${{ env.VERSION_ANCHOR }} | github changelog> for more details. \n\n\n :next: :next: :next: :bullettrain_side: \n\n\n The next pre-release will be built off the `${{ env.NEXT_RELEASE_BRANCH }}` branch, see a preview of all changes <https://github.com/sourcegraph/cody/compare/${{ env.CURRENT_RELEASE_BRANCH }}...${{ env.NEXT_RELEASE_BRANCH }} | here>"
            }' "$webhook")
            status_code=${response: -3}
            body=${response:0:${#response}-3}

            if [ "$status_code" != "200" ]; then
              echo "❌ Unable to post message to slack, got:"
              echo "--- raw body ---"
              echo "$body"
              echo "--- raw body ---"
              exit 1
            else
              echo "Posted to slack."
            fi
          done
      - name: Check if the next release branch and backport label exist
        id: check-exists
        run: |
          # Check if branch exists
          if git ls-remote --heads origin ${{ env.NEXT_RELEASE_BRANCH }} | grep -q "${{ env.NEXT_RELEASE_BRANCH }}"; then
            echo "Branch ${{ env.NEXT_RELEASE_BRANCH }} already exists"
            echo "SKIP_BRANCH_CREATION=true" >> $GITHUB_ENV
            exit 0
          fi

          # Check if label exists
          if gh label list | grep -q "backport ${{ env.NEXT_RELEASE_BRANCH }}"; then
            echo "Label backport ${{ env.NEXT_RELEASE_BRANCH }} already exists"
            echo "SKIP_LABEL_CREATION=true" >> $GITHUB_ENV
            exit 0
          fi
      - name: Create backport label
        if: ${{ !env.SKIP_LABEL_CREATION }}
        uses: actions/github-script@v6
        with:
          script: |
            const nextReleaseBranch = process.env.NEXT_RELEASE_BRANCH;
            const nextBackportLabel = `backport ${nextReleaseBranch}`;
            github.rest.issues.createLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: `${nextBackportLabel}`,
              description: `Backport to ${nextReleaseBranch} branch`
            })
      - name: Create and push next release branch
        if: ${{ !env.SKIP_BRANCH_CREATION }}
        run: |
          git checkout main
          git checkout -b ${{ env.NEXT_RELEASE_BRANCH }}

          if ! git push origin ${{ env.NEXT_RELEASE_BRANCH }}; then
            echo "Failed to push the next release branch ${{ env.NEXT_RELEASE_BRANCH }} to origin"
            exit 1
          fi
